export type IconicProject = {
  slug: string;
  title: string;
  location: string;
  value: string;
  scope: string;
  impact: string;
};

export const iconicProjects: IconicProject[] = [
  {
    slug: "wani-24x7-water",
    title: "24x7 Water Supply Scheme – Wani (Amrut 2.0)",
    location: "Yavatmal District",
    value: "₹140.62 Cr",
    scope: "Complete water distribution network with smart metering, ESRs, and IoT-based SCADA monitoring.",
    impact: "Ensures round-the-clock water access for urban and rural clusters in Yavatmal district.",
  },
  {
    slug: "indapur-cc-road",
    title: "Indapur Cement Concrete (CC) Road Project (Under MSJNM)",
    location: "Indapur",
    value: "₹104.90 Cr",
    scope: "Construction of 40+ km of CC roads, RCC drains, culverts, and LED street lighting.",
    impact: "Enhanced connectivity and improved infrastructure quality for residents.",
  },
  {
    slug: "pandharkawda-wss",
    title: "Pandharkawda Water Supply Scheme, Yavatmal District",
    location: "Yavatmal District",
    value: "₹68.44 Cr",
    scope: "Design and implementation of a regional water supply network with ESRs and pumping systems.",
    impact: "Strengthened municipal water delivery and reduced dependency on borewells.",
  },
  {
    slug: "amdapur-janephal-vishvi-cc-road",
    title: "Amdapur–Janephal–Vishvi CC Road Improvement",
    location: "Buldhana Region",
    value: "₹55.50 Cr",
    scope: "Road strengthening, concrete paving, and integrated drainage construction.",
    impact: "Boosted road safety and mobility across rural corridors.",
  },
  {
    slug: "lendi-talao-rejuvenation",
    title: "Rejuvenation & Beautification of Lendi Talao, Lonar (Amrut 2.0)",
    location: "Lonar",
    value: "₹14.31 Cr",
    scope: "Lake desilting, waterfront walkway, LED lighting, and green landscaping.",
    impact: "Restored ecological balance and promoted tourism in Lonar.",
  },
];

export type ProjectItem = {
  title: string;
  district: string;
  type?: string;
  location?: string;
  image?: string;
};

export const projectCategories = [
  { key: "roads_highways", label: "Road & Highways" },
  { key: "water_supply", label: "Water Supply" },
  { key: "urban_infra", label: "Urban Infrastructure" },
  { key: "renewable_solar", label: "Renewable Energy / Solar" },
] as const;

export const projectsByCategory: Record<(typeof projectCategories)[number]["key"], ProjectItem[]> = {
  roads_highways: [
    { title: "CC Road Beautification – Balaji Temple", type: "CC Road & Beautification", district: "Buldhana" },
    { title: "CC Road & RCC Drain – MSJNM", type: "CC Road + RCC Drain", district: "Buldhana" },
    { title: "Internal CC Roads – Bagulkhed Area", type: "Internal CC Roads", district: "Buldhana" },
    { title: "Internal CC Roads – Dongaon Area", type: "Internal CC Roads", district: "Buldhana" },
    { title: "Internal CC Roads – Sukali Area", type: "Internal CC Roads", district: "Buldhana" },
    { title: "Cement Road – Sarkari Godown (Lonar)", type: "CC Road", district: "Buldhana" },
    { title: "Village CC Roads – Mehkar & Lonar", type: "CC Road", district: "Buldhana" },
    { title: "CC Roads – Forest & Village Areas", type: "CC Road", district: "Buldhana" },
    { title: "CC Road – Mahavir Nagar (Lonar)", type: "CC Road", district: "Buldhana" },
    { title: "CC Road – Minority Colony (Lonar)", type: "CC Road", district: "Buldhana" },
    { title: "Dalit Vasti Road – Nagar Parishad Lonar", type: "Civil Road Work", district: "Buldhana" },
    { title: "SH-390 Highway Improvement", type: "Highway Improvement", district: "Buldhana" },
    { title: "Urban Development – Annabhau Sathe Yojna (Mehkar)", type: "CC Road + Drain + Open Space", district: "Buldhana" },
  ],
  renewable_solar: [
    { title: "Being 1563/gnd/2022-23, providing erecting 100 no of solar mini highmust pole… at various Grampanchayat", district: "Bhandara" },
    { title: "Providing and Erecting 23 Nos Solar Mini Highmast Pole 9 Mtrs… at various Gram Panchayat locations", district: "Bhandara" },
    { title: "Providing erecting 63 no of solar mini highmast pole…", district: "Gondia" },
    { title: "Providing and erecting LED street light at divider of DP Road at Mehkar", district: "Buldhana" },
    { title: "Providing & erecting mini solar highmast 9 mtr — various sites at Mehkar, under Dalit Wasti", district: "Buldhana" },
    { title: "Providing and Erecting 48 Nos solar mini highmast pole… under Umarkhed and Mahagaon Tahsil", district: "Yavatmal" },
    { title: "Providing and Erecting 63 Nos solar mini highmast pole… under Kalamb, Babhulgaon and Ralegaon", district: "Yavatmal" },
    { title: "Solar mini highmast pole at various Gram Panchayat locations (1564, 1566)", district: "Gondia + Bhandara" },
    { title: "Providing & erecting of solar mini highmast, solar street, Wani highmast", district: "Yavatmal" },
    { title: "Providing and erecting solar highmast pole 9 mtr with LED flood light… Umari, Amlon, Belora, Bhalar etc.", district: "Yavatmal" },
  ],
  urban_infra: [
    { title: "Construction and development of river bank flood control retaining wall to Painganga river", district: "Buldhana" },
    { title: "Repairing of schools at Anjaani, Kalyana, Jambhul, Deulgaon Kundpal and others", district: "Buldhana" },
    { title: "Repairing of health centre at Sultanpur, Tambola, Hirdav and school at Sultanpur", district: "Buldhana" },
    { title: "Construction of bridge under Gharkul programme for Lonar Nagar Parishad", district: "Buldhana" },
    { title: "Construction of parking shade, CC drain and retaining wall for tourist site (Survey 294) — Lonar", district: "Buldhana" },
    { title: "Construction of compound wall for Sharangdhar Balaji Temple", district: "Buldhana" },
    { title: "CC road, RCC drain with footpath and culverts under MSJNM — Municipal Council Indapur", district: "Pune" },
    { title: "Construction of flood protection wall at Bhalegaon", district: "Buldhana" },
    { title: "Rejuvenation & beautification of Lendi Talao, Lonar (Amrut 2.0)", district: "Buldhana" },
    { title: "Informatory sign boards at various locations within Lonar city", district: "Buldhana" },
    { title: "Beautification & development at open space in front of Gomukh Dhar, Lonar", district: "Buldhana" },
    { title: "Construction of kitchen with pantry — Civil Hospital, Buldhana", district: "Buldhana" },
    { title: "Compound wall at Anjani Bk, Fardapur, Anjani Kh & Shadikhana at Veni", district: "Buldhana" },
    { title: "Compound wall and solar lights at graveyard — Mola, Sonargavhan, Shelgaon Deshmukh, Shahapur", district: "Buldhana" },
    { title: "Compound wall along road of Balaji Mandir near Painganga river ghat", district: "Buldhana" },
    { title: "Development of tree plantation and green belts within Lonar NP limits", district: "Buldhana" },
    { title: "Furniture and electrification work for N.P. owned study center, Lonar", district: "Buldhana" },
    { title: "Compound wall to open space behind Shri Rajubhau Kate house, Prabhag 4", district: "Buldhana" },
    { title: "Renovation in crematorium near Painganga river (Prabhag 8) & crematorium at Janefal road", district: "Buldhana" },
    { title: "Construction of Sabha Mandap for Datta Mandir in Municipal Council land", district: "Buldhana" },
    { title: "Construction of Sabha Mandap and development around Martand Guru Mandir", district: "Buldhana" },
    { title: "Beautification of Chhatrapati Shivaji Maharaj Udyan", district: "Buldhana" },
    { title: "Construction of Cultural Hall, Malegaon", district: "Washim" },
    { title: "M & R to office building", district: "Nagpur" },
    { title: "Nagri Soyi Suvidha Yojna, Mehkar", district: "Buldhana" },
  ],
  water_supply: [
    { title: "ESR Lonar", district: "Buldhana" },
    { title: "Village Water Supply Scheme at Ghuti–Pardi, Tq. Mehkar", district: "Buldhana" },
    { title: "Borakhedi Water Supply Scheme, Tq. Lonar", district: "Buldhana" },
    { title: "Pachala Village Water Supply Scheme, Tal. Mehkar", district: "Buldhana" },
    { title: "Sonuna Water Supply Scheme, Tal. Lonar", district: "Buldhana" },
    { title: "Kinhi Water Supply Scheme, Tal. Lonar", district: "Buldhana" },
    { title: "Sarshiv Water Supply Scheme, Tal. Mehkar", district: "Buldhana" },
    { title: "Bramapuri Water Supply Scheme, Tal. Mehkar", district: "Buldhana" },
    { title: "Anjani augmentation to Anjani WSS, Tq. Mehkar", district: "Buldhana" },
    { title: "Loni Gawali Water Supply Scheme, Tq. Mehkar", district: "Buldhana" },
    { title: "Deulgaon Kundpal WSS, Tal. Lonar", district: "Buldhana" },
    { title: "Saokhed Bhoi WSS, Tq. Deulgaon Raja", district: "Buldhana" },
    { title: "Bhivgaon–Jumda WSS, Tq. Deulgaon Raja", district: "Buldhana" },
    { title: "Andhera & 9 Villages RRWS Scheme", district: "Buldhana" },
    { title: "Ghatbori WSS, Tq. Mehkar", district: "Buldhana" },
    { title: "Bhumrala WSS, Tq. Mehkar", district: "Buldhana" },
    { title: "Sabra WSS, Tq. Mehkar", district: "Buldhana" },
    { title: "Sonargavhan WSS, Tq. Motala", district: "Buldhana" },
    { title: "Jaytala WSS, Tq. Mehkar", district: "Buldhana" },
    { title: "Pipeline from filter plant to T‑point, MC Sindkhed Raja", district: "Buldhana" },
    { title: "Pimprimali WSS, Tq. Lonar", district: "Buldhana" },
    { title: "Saraswati WSS, Tq. Lonar", district: "Buldhana" },
    { title: "Pimpalkutta & Matmal WSS, Tq. Lonar", district: "Buldhana" },
    { title: "Gohgaon WSS, Tq. Mehkar", district: "Buldhana" },
    { title: "Titvi WSS, Tq. Lonar", district: "Buldhana" },
    { title: "Kambarkhed & Gavandhala WSS, Tq. Mehkar", district: "Buldhana" },
    { title: "Andrud WSS, Tq. Mehkar", district: "Buldhana" },
    { title: "Rohna WSS, Tq. Deulgaon Raja", district: "Buldhana" },
    { title: "Asola–Jahagir WSS, Tq. Deulgaon Raja", district: "Buldhana" },
    { title: "Jawalkhed WSS, Tq. Deulgaon Raja", district: "Buldhana" },
    { title: "Gondhankhed WSS, Tq. Deulgaon Raja", district: "Buldhana" },
    { title: "RCC ESR 5 lakh lit – Pandharkawda", district: "Yavatmal" },
    { title: "Sawatara WSS, Tq. Mehkar", district: "Buldhana" },
    { title: "Pentakli WSS, Tq. Mehkar", district: "Buldhana" },
    { title: "Tandali Bk WSS", district: "Akola" },
    { title: "Yelgaon & 2 Villages RRWSS", district: "Buldhana" },
    { title: "Hirabambai & 5 Villages RRWSS (JJM), Tq. Dharni", district: "Amravati" },
    { title: "Ranapisa & 7 Villages RRWSS (JJM), Tq. Dharni", district: "Amravati" },
    { title: "Loni Kale & 7 Villages RRWSS (JJM)", district: "Buldhana" },
    { title: "Landewadi WSS, Tq. Mehkar", district: "Buldhana" },
    { title: "Durgbori WSS, Tq. Mehkar", district: "Buldhana" },
    { title: "Payghanwadi WSS, Tq. Mehkar", district: "Buldhana" },
    { title: "Karalwadi WSS, Tq. Mehkar", district: "Buldhana" },
    { title: "Mosheambewade WSS, Tq. Mehkar", district: "Buldhana" },
    { title: "Kingaon Jattu WSS, Tq. Lonar", district: "Buldhana" },
    { title: "Meljanori WSS (JJM), Tq. Mehkar", district: "Buldhana" },
    { title: "Mundefal WSS (JJM), Tq. Mehkar", district: "Buldhana" },
    { title: "Wadgaon Tejan WSS (JJM), Tq. Lonar", district: "Buldhana" },
    { title: "Warud Amravati Scheme", district: "Amravati" },
    { title: "Mangarul (I) WSS, Tq. Chikhali (JJM)", district: "Buldhana" },
    { title: "Sawangi Mali WSS, Tq. Mehkar", district: "Buldhana" },
    { title: "Ghuti–Pardi WSS, Tq. Mehkar", district: "Buldhana" },
    { title: "Shelgaon Atol & Pimpalwadi WSS, Tq. Chikhli", district: "Buldhana" },
    { title: "Khalegaon WSS, Tq. Lonar", district: "Buldhana" },
    { title: "Under JJM Aug to Asgaon village WSS, Tal. Pauni", district: "Bhandara" },
    { title: "Churni WSS", district: "Amravati" },
    { title: "Vitthalwadi WSS, Tq. Mehkar", district: "Buldhana" },
    { title: "Tandali Khurd WSS", district: "Washim" },
    { title: "Under JJM Aug to Adyal village WSS, Tal. Pauni", district: "Bhandara" },
    { title: "Dudha & 2 villages WSS, Tq. Mehkar", district: "Buldhana" },
    { title: "Belgaon Mehkar WSS, Tq. Mehkar", district: "Buldhana" },
    { title: "Warud WSS, Tq. Mehkar", district: "Buldhana" },
    { title: "Pachala WSS (duplicate consolidated)", district: "Buldhana" },
    { title: "Achalpur WSS", district: "Amravati" },
    { title: "Maneri WSS, Tah. Sadak Arjuni", district: "Gondia" },
    { title: "Aug to Fattepur WSS, Tah. Gondia", district: "Gondia" },
    { title: "Aug to Gangla WSS, Tah. Tiroda", district: "Gondia" },
    { title: "Aug to Mangezari WSS, Tah. Tiroda", district: "Gondia" },
    { title: "Aug to Dhadari & Umari WSS, Tah. Tiroda", district: "Gondia" },
    { title: "Khadipur WSS", district: "Gondia" },
    { title: "Shara WSS, Tq. Lonar", district: "Buldhana" },
    { title: "M & R to Mahaadula Water Supply Scheme", district: "Nagpur" },
    { title: "Pandharkawada WSS (MSJNM)", district: "Yavatmal" },
    { title: "Wani Amrut 2.0 Water Supply Scheme — Wani Municipal Council", district: "Yavatmal" },
    { title: "Daund Water Supply Scheme — Part 1 (Amrut 2.0)", district: "Pune" },
    { title: "Daund Water Supply Scheme — Part 2 (Amrut 2.0)", district: "Pune" },
  ],
  roads_highways: [
    { title: "PROPOSED CONSTRUCTION AND BEUTIFICATION OF C C ROAD FOR PRACHIN SHARANGDHAR BALAJI TEMPLE", district: "Buldhana" },
    { title: "Construction of C.C. Road, R.C.C. Drain With Footpath and Culverts In Prabhag - 1, 4, 9, 11, and 12 Under MSJNM", district: "Buldhana" },
    { title: "Construction of Internal Cement concrete road Bagulkhed, Matarkhed, Saraswati, Dhanora, Shara etc, Dist. Buldhana", district: "Buldhana" },
    { title: "Construction of Internal Cement concrete road at Miskinwadi, Mosanbewadi, Vivekananad, Dongaon, Ukali, Loni Gawali etc. dist. Buldhana", district: "Buldhana" },
    { title: "Construction of Internal Cement concrete road at Sukali, Antri Deshmukh, Sultanpur etc, Dist. Buldhana", district: "Buldhana" },
    { title: "proposed cosntruction of cement road from sarkari godown to shaikh aran house at lonar for MC lonar dist buldhana", district: "Buldhana" },
    { title: "const of internal cc road tembhurkhed, rajgad, wadali, tq. Mehkar and const of cc road at titvi tq. lonar dist.buldhana", district: "Buldhana" },
    { title: "const of cc road mandawa forest, ratnapur, lawana, malegaon, pathrdji tq. Mehkar and const off cc road at pahur tq. Lonar dist buldhana", district: "Buldhana" },
    { title: "Construction of CC Road in Mahavir Nagar, Lonar", district: "Buldhana" },
    { title: "const of cc road in minority colony at pimpalner lonar dist buldhana", district: "Buldhana" },
    { title: "CIVIL WORK 2 FOR NAGAR PARISHAD LONAR dalit vasti road", district: "Buldhana" },
    { title: "IMPROVEMENT TO AMDAPUR-JANEPHAL-LONIGAWLI-GHATBORI… ROAD SH 390 (major highway work)", district: "Buldhana" },
    { title: "Construction of CC Road Providing RCC Drain Construction of Paver Block road and Development of Open Space under Annabhau Sathe Yojna Mehkar", district: "Buldhana" },
  ],
};
