export type IconicProject = {
  slug: string;
  title: string;
  location: string;
  value: string;
  scope: string;
  impact: string;
};

export const iconicProjects: IconicProject[] = [
  {
    slug: "wani-24x7-water",
    title: "24x7 Water Supply Scheme – Wani (Amrut 2.0)",
    location: "Yavatmal District",
    value: "₹140.62 Cr",
    scope: "Complete water distribution network with smart metering, ESRs, and IoT-based SCADA monitoring.",
    impact: "Ensures round-the-clock water access for urban and rural clusters in Yavatmal district.",
  },
  {
    slug: "indapur-cc-road",
    title: "Indapur Cement Concrete (CC) Road Project (Under MSJNM)",
    location: "Indapur",
    value: "₹104.90 Cr",
    scope: "Construction of 40+ km of CC roads, RCC drains, culverts, and LED street lighting.",
    impact: "Enhanced connectivity and improved infrastructure quality for residents.",
  },
  {
    slug: "pandharkawda-wss",
    title: "Pandharkawda Water Supply Scheme, Yavatmal District",
    location: "Yavatmal District",
    value: "₹68.44 Cr",
    scope: "Design and implementation of a regional water supply network with ESRs and pumping systems.",
    impact: "Strengthened municipal water delivery and reduced dependency on borewells.",
  },
  {
    slug: "amdapur-janephal-vishvi-cc-road",
    title: "Amdapur–Janephal–Vishvi CC Road Improvement",
    location: "Buldhana Region",
    value: "₹55.50 Cr",
    scope: "Road strengthening, concrete paving, and integrated drainage construction.",
    impact: "Boosted road safety and mobility across rural corridors.",
  },
  {
    slug: "lendi-talao-rejuvenation",
    title: "Rejuvenation & Beautification of Lendi Talao, Lonar (Amrut 2.0)",
    location: "Lonar",
    value: "₹14.31 Cr",
    scope: "Lake desilting, waterfront walkway, LED lighting, and green landscaping.",
    impact: "Restored ecological balance and promoted tourism in Lonar.",
  },
];

export type ProjectItem = {
  title: string;
  district: string;
  type?: string;
  location?: string;
  image?: string;
};

export const projectCategories = [
  { key: "roads_highways", label: "Road & Highways" },
  { key: "water_supply", label: "Water Supply" },
  { key: "urban_infra", label: "Urban Infrastructure" },
  { key: "renewable_solar", label: "Renewable Energy / Solar" },
] as const;

export const projectsByCategory: Record<(typeof projectCategories)[number]["key"], ProjectItem[]> = {
  roads_highways: [
    { title: "CC Road Beautification – Balaji Temple", district: "Buldhana" },
    { title: "CC Road & Drain Work – MSJNM", district: "Buldhana" },
    { title: "Internal CC Roads – Bagulkhed Area", district: "Buldhana" },
    { title: "Internal CC Roads – Dongaon Area", district: "Buldhana" },
    { title: "Internal CC Roads – Sukali Area", district: "Buldhana" },
    { title: "Cement Road – Sarkari Godown", district: "Buldhana" },
    { title: "Village CC Roads – Mehkar & Lonar", district: "Buldhana" },
    { title: "CC Roads – Forest & Village Areas", district: "Buldhana" },
    { title: "CC Road – Mahavir Nagar", district: "Buldhana" },
    { title: "CC Road – Minority Colony", district: "Buldhana" },
    { title: "Dalit Vasti Road – Lonar", district: "Buldhana" },
    { title: "SH-390 Highway Improvement", district: "Buldhana" },
    { title: "Urban Development – Mehkar", district: "Buldhana" },
  ],
  renewable_solar: [
    { title: "Solar Mini Highmast Poles – Gram Panchayats", district: "Bhandara" },
    { title: "Solar Mini Highmast Poles (23 Nos)", district: "Bhandara" },
    { title: "Solar Mini Highmast Poles (63 Nos)", district: "Gondia" },
    { title: "LED Street Lighting – DP Road, Mehkar", district: "Buldhana" },
    { title: "Solar Mini Highmast – Dalit Wasti, Mehkar", district: "Buldhana" },
    { title: "Solar Mini Highmast Poles – Umarkhed & Mahagaon", district: "Yavatmal" },
    { title: "Solar Mini Highmast Poles – Kalamb, Babhulgaon & Ralegaon", district: "Yavatmal" },
    { title: "Solar Mini Highmast Poles – Gondia & Bhandara", district: "Gondia / Bhandara" },
    { title: "Solar Highmast Street Lighting – Wani", district: "Yavatmal" },
    { title: "Solar Highmast Poles with LED Flood Lights – Village Cluster", district: "Yavatmal" },
  ],
  urban_infra: [
    { title: "Painganga River Bank Development & Flood Control", district: "Buldhana" },
    { title: "Bridge Construction – Gharkul Program (Lonar)", district: "Buldhana" },
    { title: "Tourist Parking Shade & Retaining Wall – Lonar", district: "Buldhana" },
    { title: "Compound Wall – Sharangdhar Balaji Temple", district: "Buldhana" },
    { title: "CC Road & Drain Work – Indapur (MSJNM)", district: "Pune" },
    { title: "Flood Protection Wall – Bhalegaon", district: "Buldhana" },
    { title: "Lendi Talao Rejuvenation & Beautification (AMRUT 2.0)", district: "Buldhana" },
    { title: "Informatory Sign Boards – Lonar City", district: "Buldhana" },
    { title: "Open Space Development – Gomukh Dhar, Lonar", district: "Buldhana" },
    { title: "Compound Walls & Shadikhana Construction", district: "Buldhana" },
    { title: "Compound Wall & Solar Lights – Graveyards", district: "Buldhana" },
    { title: "Compound Wall Near Balaji Mandir – Painganga Ghat", district: "Buldhana" },
    { title: "Tree Plantation & Green Belt Development – Lonar", district: "Buldhana" },
    { title: "Furniture & Electrification – Study Center Lonar", district: "Buldhana" },
    { title: "Compound Wall – Open Space (Prabhag 4)", district: "Buldhana" },
    { title: "Smashanbhumi Renovation – Painganga & Janefal Road", district: "Buldhana" },
    { title: "Sabha Mandap – Datta Mandir", district: "Buldhana" },
    { title: "Sabha Mandap & Area Development – Martand Guru Mandir", district: "Buldhana" },
    { title: "Chhatrapati Shivaji Maharaj Udyan Beautification", district: "Buldhana" },
    { title: "Office Building Maintenance & Repair", district: "Nagpur" },
    { title: "Nagri Soyi Suvidha Yojna – Mehkar", district: "Buldhana" },
  ],
  water_supply: [
    { title: "ESR – Lonar", district: "Buldhana" },
    { title: "Village Water Supply – Ghuti-Pardi", district: "Buldhana" },
    { title: "Borakhedi Water Supply Scheme", district: "Buldhana" },
    { title: "Pachala Water Supply Scheme", district: "Buldhana" },
    { title: "Sonuna Water Supply Scheme", district: "Buldhana" },
    { title: "Kinhi Water Supply Scheme", district: "Buldhana" },
    { title: "Sarshiv Water Supply Scheme", district: "Buldhana" },
    { title: "Bramhapuri Water Supply Scheme", district: "Buldhana" },
    { title: "Anjani Water Supply Augmentation", district: "Buldhana" },
    { title: "Loni Gawali Water Supply Scheme", district: "Buldhana" },
    { title: "Deulgaon Kundpal Water Supply Scheme", district: "Buldhana" },
    { title: "Saokhed Bhoi Water Supply Scheme", district: "Buldhana" },
    { title: "Bhivgaon–Jumda Water Supply Scheme", district: "Buldhana" },
    { title: "Andhera Regional Water Supply Scheme", district: "Buldhana" },
    { title: "Ghatbori Water Supply Scheme", district: "Buldhana" },
    { title: "Bhumrala Water Supply Scheme", district: "Buldhana" },
    { title: "Sabra Water Supply Scheme", district: "Buldhana" },
    { title: "Sonargavhan Water Supply Scheme", district: "Buldhana" },
    { title: "Jaytala Water Supply Scheme", district: "Buldhana" },
    { title: "Pipeline Work – Sindkhed Raja MC", district: "Buldhana" },
    { title: "Pimprimali Water Supply Scheme", district: "Buldhana" },
    { title: "Saraswati Water Supply Scheme", district: "Buldhana" },
    { title: "Pimpalkutta–Matmal Water Supply Scheme", district: "Buldhana" },
    { title: "Gohgaon Water Supply Scheme", district: "Buldhana" },
    { title: "Titvi Water Supply Scheme", district: "Buldhana" },
    { title: "Kambarkhed–Gavandhala Water Supply Scheme", district: "Buldhana" },
    { title: "Andrud Water Supply Scheme", district: "Buldhana" },
    { title: "Rohna Water Supply Scheme", district: "Buldhana" },
    { title: "Asola–Jahagir Water Supply Scheme", district: "Buldhana" },
    { title: "Jawalkhed Water Supply Scheme", district: "Buldhana" },
    { title: "Gondhankhed Water Supply Scheme", district: "Buldhana" },
    { title: "RCC ESR – Pandharkawada", district: "Yavatmal" },
    { title: "Sawatra Water Supply Scheme", district: "Buldhana" },
    { title: "Pentakli Water Supply Scheme", district: "Buldhana" },
    { title: "Tandali Bk Water Supply Scheme", district: "Akola" },
    { title: "Yelgaon Regional Water Supply Scheme", district: "Buldhana" },
    { title: "Hirabambai Regional Water Supply Scheme", district: "Amravati" },
    { title: "Ranapisa Regional Water Supply Scheme", district: "Amravati" },
    { title: "Loni Kale Regional Water Supply Scheme", district: "Buldhana" },
    { title: "Landewadi Water Supply Scheme", district: "Buldhana" },
    { title: "Durgbori Water Supply Scheme", district: "Buldhana" },
    { title: "Payghanwadi Water Supply Scheme", district: "Buldhana" },
    { title: "Karalwadi Water Supply Scheme", district: "Buldhana" },
    { title: "Mosheambewade Water Supply Scheme", district: "Buldhana" },
    { title: "Kingaon Jattu Water Supply Scheme", district: "Buldhana" },
    { title: "Meljanori Water Supply Scheme (JJM)", district: "Buldhana" },
    { title: "Mundefal Water Supply Scheme (JJM)", district: "Buldhana" },
    { title: "Wadgaon Tejan Water Supply Scheme (JJM)", district: "Buldhana" },
    { title: "Warud Water Supply Scheme", district: "Amravati" },
    { title: "Mangaruli Water Supply Scheme (JJM)", district: "Buldhana" },
    { title: "Sawangi Mali Water Supply Scheme", district: "Buldhana" },
    { title: "Ghuti-Pardi Water Supply Scheme", district: "Buldhana" },
    { title: "Shelgaon Atol–Pimpalwadi Water Supply Scheme", district: "Buldhana" },
    { title: "Khalegaon Water Supply Scheme", district: "Buldhana" },
    { title: "Asgaon Water Supply Augmentation (JJM)", district: "Bhandara" },
    { title: "Churni Water Supply Scheme", district: "Amravati" },
    { title: "Vitthalwadi Water Supply Scheme", district: "Buldhana" },
    { title: "Tandali Khurd Water Supply Scheme", district: "Washim" },
    { title: "Adyal Water Supply Augmentation (JJM)", district: "Bhandara" },
    { title: "Dudha Water Supply Scheme", district: "Buldhana" },
    { title: "Belgaon Mehkar Water Supply Scheme", district: "Buldhana" },
    { title: "Warud Water Supply Scheme – Mehkar", district: "Buldhana" },
    { title: "Pachala Water Supply Scheme (Phase-2)", district: "Buldhana" },
    { title: "Achalpur Water Supply Scheme", district: "Amravati" },
    { title: "Maneri Water Supply Scheme", district: "Gondia" },
    { title: "Fattepur Water Supply Augmentation", district: "Gondia" },
    { title: "Gangla Water Supply Augmentation", district: "Gondia" },
    { title: "Mangezari Water Supply Augmentation", district: "Gondia" },
    { title: "Dhadari–Umari Water Supply Scheme", district: "Gondia" },
    { title: "Khadipur Water Supply Scheme", district: "Gondia" },
    { title: "Shara Water Supply Scheme", district: "Buldhana" },
    { title: "Mahaadula Water Supply M&R Work", district: "Nagpur" },
    { title: "Pandharkawada Water Supply Scheme (MSJNM)", district: "Yavatmal" },
    { title: "Wani AMRUT 2.0 Water Supply Scheme", district: "Yavatmal" },
    { title: "Daund Water Supply Scheme – Part 1 (AMRUT 2.0)", district: "Pune" },
    { title: "Daund Water Supply Scheme – Part 2 (AMRUT 2.0)", district: "Pune" },
  ]
};
